### ISSUE TITLE
Fehleranzeige Voting

### ISSUE THREAD

**Issue by Mirco1977** [Co1002/Bandenkick-Project#11]
Im Management wird nach Schließung Voting folgendes angezeigt:

Fatal error: Uncaught Error: Call to undefined function getCountryFlagWithCca2() in /homepages/31/d866349292/htdocs/management.bel-ligen.de/templates/votingList.php:53 Stack trace: #0.....

/homepages/31/d866349292/htdocs/management.bel-ligen.de/templates/votingList.php on line 53

**Comment by Co1002** [comment]
Fixed
