### ISSUE TITLE
1vs1 Def Rückwirkend

### ISSUE THREAD

**Issue by Mirco1977** [Co1002/Bandenkick-Project#3]
In 1vs1 Liga können Spiele der Vergangenheit mit Teams welche aufgelöst wurden nicht in ein Def umgewandelt werden, wenn das Team weder Spieler noch Manager hat.
Beispiel: BEL2 1vs1 Spieltag1 8:0 Borussia DOesp Defwin.

**Comment by Co1002** [comment]
Spieler müssen ab sofort im 1vs1, genau wie im clubs-modus, nun nicht merh bei defs selektiert werden.
